### ISSUE TITLE
Explore smart paste/drag-drop adoption across remaining surfaces

### ISSUE THREAD

**Issue by abyssrift** [abyssrift/TrustFlow#326]
## Context
Issue #319 shipped smart clipboard/drag-drop primitives that intelligently route Ctrl+V and OS file drag-drop into the right create/upload flows. Phases 1–4 (+ 3.5 global affordance) are complete and on `experimental`.

## New primitives available

- **`useSmartPaste({onFiles, onText}, enabled)`** — web-only hook; files always intercepted (can't paste image into a textarea), text passes through to focused inputs or routes to `onText` handler.
- **`useFileDrop(...) → { ref, isOver, isDragActive }`** — third return field `isDragActive` (module-scope global drag-active counter, OS-file drags only).
- **`<FileDropOverlay active over label />`** — the reusable drop affordance. Idle breathe at half amplitude when `active`, escalates to full FileHub pulse on `over`. Gated on `useReducedMotion()`.
- **Shared seed effect pattern** — `CreateTaskModal` accepts `initialText` / `initialFiles` props; Tasks screens open the composer pre-seeded from screen-level paste/drop.

## Known deferred surfaces (same one-line swap)

- `components/task-detail/TaskBriefPanel.tsx` — task-detail file attachment
- `components/task-detail/StageActions.tsx` — submission evidence attachment
- `components/intelligence/_filehub_desktop.tsx` — UploadModal inner drop zone

## Exploration needed

Screen the codebase for other file/content creation surfaces that would benefit from smart paste/drag-drop seeding. Look for:
1. Modals / sheets that attach files or accept input (portfolios, projects, submissions, templates, settings, avatars, etc.)
2. Inline drop zones or file pickers that could show the unified `FileDropOverlay` affordance
3. Text input fields (descriptions, notes, titles) that could auto-fill from pasted text
4. Surfaces that currently require manual "pick a file, then open modal" workflows

## Suggested approach
- Use `graphify query "file upload" / "create modal" / "file picker"` to map the existing surfaces
- Document findings in a follow-up issue or checklist (per-phase adoption, grouped by surface type)
- Prioritize high-traffic paths (common tasks, frequent workflows) over edge-case settings

**Not in scope:** Phase 5 deferred work (dropped-text handling, native Tasks affordance, narrow-web FileHub paste). Those are separate.

## Acceptance
A list of recommended surfaces + estimated effort per surface (one-liner swap, new seed props, full integration). Can be a checklist or a ranked table. No implementation — exploration only.

**Comment by abyssrift** [comment]
## New surface introduced by #340: standalone `UploadComposerModal`

#340 extracted the FileHub upload composer into `components/filehub/UploadComposerModal.web.tsx` (summoned by ModalHost / command palette / QuickCreateButton / `?type=upload` deep link). The screen-local `UploadModal` in `_filehub_desktop.tsx` was deliberately left in place, so the two now diverge on smart-paste support:

| | old screen-local `UploadModal` | new `UploadComposerModal` (#340) |
|---|---|---|
| in-modal drag-drop zone | yes | yes (`useFileDrop`, line ~322) |
| screen-level paste/drop → opens pre-seeded | yes — `_filehub_desktop.tsx` routes `useSmartPaste`/`useFileDrop` → `setDroppedFiles` → `initialFiles` | **no** — no `initialFiles` prop, no seed effect |
| Ctrl+V while modal open adds file | via screen-level handler | **no** — no `useSmartPaste` |

### Gap
When the new composer is opened via palette / QuickCreate / deep link, there's no way to hand it files already on the clipboard or dragged in — you land on an empty staging UI and have to use the picker. The #319 seed path only feeds the old modal.

### Fix (same one-line-swap pattern as the rest of #326)
1. Add `initialFiles?: File[]` (and optionally `initialText`) to `UploadComposerModalProps`, mirror the `CreateTaskModal` seed effect: on `visible` transition, `setDraft(prev => ({ ...prev, files: [...initialFiles] }))`.
2. Add `useSmartPaste({ onFiles: … }, visible)` inside the modal so Ctrl+V works when it's focused/open.
3. Thread `initialFiles` through ModalHost's `'upload'` case + `useModalQueryParam` payload (params can't carry File objects, so this is for in-app `summon('upload', { initialFiles })` callers — the FileHub screen's paste/drop handler should call that instead of its local `UploadModal` once parity exists, then the old modal can be deleted per #340's own follow-up note).

**Comment by abyssrift** [comment]
Claiming this issue — starting work now.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by abyssrift** [comment]
Exploration acceptance criteria were completed by PR #366 and docs/audit/smart-paste-adoption-audit.md. The highest-priority FileHub consolidation has now been implemented and verified under #351; global undo remains tracked separately in #138 and the navigation abort overlay in #390.
